export const IconsMap =
{ 'credito'               : 'icon-diamond'
, 'grupo'                 : 'icon-users'
, 'participantes'         : 'icon-users'
, 'ideia'                 : 'icon-lamp'
, 'ideia-aprovada'        : 'icon-fire'
, 'medalha'               : 'icon-medal'
, 'pesquisa'              : 'icon-lab'
, 'plataforma'            : 'icon-rocket'
, 'portfolio'             : 'icon-target'
, 'sysop'                 : 'icon-streetlight'
, 'ajuda'                 : 'fa-question'
, 'moderador'             : 'icon-gavel'
, 'sponsor'               : 'icon-suitcase'
, 'timer'                 : 'icon-stopwatch'
, 'editar'                : 'icon-edit'
, 'aprovar-agente'        : 'icon-user-check'
, 'agente'                : 'icon-user'
, 'localizacao'           : 'icon-earth'
, 'funcao'                : 'fa-sitemap'
, 'conexoes'              : 'icon-shrink'
, 'avaliacoes'            : 'icon-clipboard'
, 'avaliacao-disrupcao'   : 'icon-atom'
, 'avaliacao-dificuldade' : 'icon-direction'
, 'avaliacao-impacto'     : 'icon-bomb'
, 'avaliacao-retorno'     : 'icon-dollar'
, 'avaliacao-tempo'       : 'icon-hour-glass'
, 'atualizar'             : 'icon-redo'
, 'price-equal'           : 'icon-arrow-circle-right'
, 'fechar'                : 'icon-cross'
, 'pc'                    : 'fa fa-desktop'
, 'reply'                 : 'icon-undo'
, 'share'                 : 'icon-share'
, 'notificacao'           : 'fa-bell'
, 'apoio-institucional'   : 'fa-feather-alt'
, 'apoio-financeiro'      : 'icon-diamond'
, 'organization'          : 'fa-building'

, 'price-up'              : 'icon-arrow-up'
, 'price-down'            : 'icon-arrow-down'
, 'google-drive'          : 'icon-google-drive'
, 'upload'                : 'icon-upload'
, 'lupa'                  : 'icon-magnifier'
, 'ellipsis'              : 'icon-ellipsis'
, 'checkmark'             : "icon-checkmark"
, 'cancel'                : "icon-cancel"
, 'question'              : "icon-question"
, 'smile'                 : "icon-smile"
, 'neutral'               : "icon-neutral"
, 'sad'                   : "icon-sad"
, 'lock'                  : "icon-lock"
, 'suitcase'              : "icon-suitcase"
, 'pushpin'               : "icon-pushpin"
, 'diamond'               : "icon-diamond"
, 'fire'                  : "icon-fire"
, 'stats'                 : "icon-stats"
, 'stats2'                : "icon-stats2"
, 'chart'                 : "icon-chart"
, 'notice'                : "icon-notice"
, 'filter'                : "icon-filter"
, 'busca'                 : "icon-busca"
, 'heart'                 : "icon-heart"
, 'undo'                  : "icon-undo"
, 'flag'                  : "icon-flag"
, 'infinite'              : "icon-infinite"
, 'image'                 : "icon-image"
, 'plus'                  : "icon-plus"

}